services:
  express-app:
    image: leovuo/express-app:latest
    container_name: express-app
    ports:
      - "8080:8080"  # adjust to match your app's listening port
    restart: always

  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 30  # check for updates every 30 seconds (optional)
